steps:
  - label: "Trigger Pipeline for timeout test"
    command: buildkite-agent pipeline upload .buildkite/trigger.yml
    key: my-trigger-pipeline
    env:
      APP_NAME: "marketplacer"
      ALIAS: "staging-au"
      DEPLOY_QUEUE: "default"
      BUILD_TIME_OUT: 30
    branches: "main"
